# Задание 1.1

In [6]:
import numpy as np

In [8]:
a = np.array([i for i in range(12, 24)])
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [10]:
a.shape

(12,)

In [12]:
a1 = a.reshape(2, 6)
a1

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [13]:
a2 = a.reshape(3, 4)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [14]:
a3 = a.reshape(4, 3)
a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [15]:
a4 = a.reshape(6, 2)
a4

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [16]:
a5 = a.reshape(1, 12)
a5

array([[12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [20]:
a6 = a.reshape(12, 1)
a6.shape

(12, 1)

In [22]:
arrays = [a.reshape(i, -1) for i in (1, 2, 3, 4, 6, 12)]
for arr in arrays:
    print(arr)
    print(arr.shape)

[[12 13 14 15 16 17 18 19 20 21 22 23]]
(1, 12)
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
(2, 6)
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
(3, 4)
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
(4, 3)
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
(6, 2)
[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]
(12, 1)


In [23]:
arrays = [a.reshape(-1, i) for i in (1, 2, 3, 4, 6, 12)]
for arr in arrays:
    print(arr)
    print(arr.shape)

[[12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]
(12, 1)
[[12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
(6, 2)
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]
(4, 3)
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
(3, 4)
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
(2, 6)
[[12 13 14 15 16 17 18 19 20 21 22 23]]
(1, 12)


Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?


нет, потому что у него 2 измерения - строки и столбцы. Метод shape вернет 2 значения (1, 12) и доступ к элементам такого массива происходит через 2 индекса

In [27]:
d = arrays[5]
d[0, 5]

17

# Задание 1.2

In [41]:
a = np.random.randn(3, 4)
print(a)
print(a.size)

[[-1.05650543 -1.21062332 -1.35754561 -1.17116226]
 [-0.01761572  0.96236973 -0.67826519  0.65980015]
 [-0.20103997  1.27367005  1.35533206  1.83655744]]
12


In [42]:
b = a.reshape(1, -1)[0]
print(b)
print(b.size)

[-1.05650543 -1.21062332 -1.35754561 -1.17116226 -0.01761572  0.96236973
 -0.67826519  0.65980015 -0.20103997  1.27367005  1.35533206  1.83655744]
12


# Задание 1.3

In [37]:
a = np.arange(20, 0, -2)
print(a)

[20 18 16 14 12 10  8  6  4  2]


In [38]:
b = np.arange(20, 1, -2).reshape(1, -1)
print(b)

[[20 18 16 14 12 10  8  6  4  2]]


В чем разница между массивами a и b?
Разница в том, что массив A одномерный, массив B - двумерный, что подтверждает метод shape

In [39]:
print(a.shape)
print(a.ndim)
print(b.shape)
print(b.ndim)

(10,)
1
(1, 10)
2


# Задание 1.4

In [45]:
a = np.zeros((2, 2))
b = np.ones((3, 2))
v = np.concatenate((a, b), axis = 0)
print(v)
print(v.size)

[[0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
10


# Задание 1.5

In [50]:
a = np.arange(12)
a = a.reshape(4, 3)
At = a.transpose()
print(a)
print(At)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


In [49]:
B = np.dot(a, At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [52]:
np.linalg.det(B)

0.0

In [54]:
B.shape

(4, 4)

Получится ли вычислить обратную матрицу для матрицы B и почему?
Не получится вычислить обратную матрицу, потому что ее не существует т.к. определитель матрицы равен 0

# Задание 1.6

In [55]:
np.random.seed(42)
c = np.random.randint(0, 16, 16)
C = c.reshape(4, 4)
C

array([[ 6,  3, 12, 14],
       [10,  7, 12,  4],
       [ 6,  9,  2,  6],
       [10, 10,  7,  4]])

In [56]:
D = np.dot(C, 10) + B
D

array([[ 65,  44, 143, 172],
       [114, 120, 206, 162],
       [ 83, 176, 169, 272],
       [132, 222, 282, 342]])

In [57]:
np.linalg.det(D)

-28511999.999999944

In [58]:
np.linalg.matrix_rank(D)

4

In [67]:
D_inv = np.linalg.inv(D)
D_inv

array([[ 0.00935396,  0.04486532,  0.05897517, -0.07286055],
       [-0.01503577, -0.00122896, -0.00192971,  0.00967873],
       [-0.00356692, -0.01782828, -0.04152146,  0.04326178],
       [ 0.00909091, -0.00181818,  0.01272727, -0.01090909]])

# Задание 1.7

In [68]:
D_inv = np.where(D_inv < 0, 0, 1)
D_inv

array([[1, 1, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [1, 0, 1, 0]])

In [69]:
E = np.where(D_inv, B, C)
E

array([[  5,  14,  23,  14],
       [ 10,   7,  12, 122],
       [  6,   9,   2, 212],
       [ 32,  10, 212,   4]])

# Задание 2

In [89]:
a = np.array([[1, 2, 3, 3, 1], [6, 8, 11, 10, 7]])
a = a.transpose()
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [90]:
mean_a = np.mean(a, axis = 0)
mean_a

array([2. , 8.4])

# Задание 3

In [91]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

# Задание 4

In [93]:
a_t = a_centered.transpose()
a_t

array([[-1. ,  0. ,  1. ,  1. , -1. ],
       [-2.4, -0.4,  2.6,  1.6, -1.4]])

In [94]:
a_centered_sp = a_t[0] @ a_t[1]
a_centered_sp

8.0

In [99]:
cov_value = a_centered_sp / (a_centered.shape[0] - 1)
cov_value

2.0

# Задание 5

In [100]:
np.cov(a_t)

array([[1. , 2. ],
       [2. , 4.3]])

In [101]:
cov_value_2 = np.cov(a_t)[0, 1]
cov_value_2

2.0